apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-1
  namespace: {{ $.Values.deploy.argo_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    avp.kubernetes.io/path: "secrets.enc.yaml"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - FailOnSharedResource=true
    retry:
      limit: 0
  destination:
    server: {{ $.Values.spec.destination.server }}
    namespace: {{ $.Values.deploy.namespace }}
  project: {{ $.Values.deploy.project }}
  source:
    path: argocd-vault-plugin/helm-chart
    repoURL:
    targetRevision: HEAD
    plugin:
      env:
        - name: AVP_TYPE
          value: sops
        - name: SOPS_AGE_KEY_FILE
          value: /age-private-key/age-key.txt
        - name: some_var
          value: <test>
      name: argocd-vault-plugin-helm
{{/*    helm:*/}}
{{/*      valueFiles:*/}}
{{/*        - secrets+age-import://secrets.enc.yaml*/}}
{{/*        - secrets.yaml*/}}
{{/*        - secrets+gpg-import:///helm-secrets-private-keys/key.asc?secrets.enc.yaml*/}}
