apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd-arsh1018
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  project: default
  source:
    repoURL:
    path: argocd-vault-plugin/working-config/apps
    targetRevision: HEAD
    plugin:
      env:
        - name: AVP_TYPE
          value: sops
#        - name: SOPS_AGE_KEY_FILE
#          value: /age-private-key/age-key.txt
      name: argocd-vault-plugin-helm
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tmnl-2
